version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Mongo Express (Web UI for MongoDB)
  mongo-express:
    image: mongo-express
    env_file:
      - ./backend/.env
    container_name: mongo_express_container
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

  # Node.js Backend Service
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules # Avoid overwriting node_modules
    command: ["npm", "run", "dev"] # Enable hot reload with Nodemon

  # React Frontend Service
  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid overwriting node_modules
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0 # Fixes hot reload issue in React
    command: ["npm", "start"] # Start React app

volumes:
  mongo_data:
